x-casaos:
  author: "MaskenNetwork"
  category: "Utility"
  icon: "https://raw.githubusercontent.com/MaskenNetwork/DVR_Markers2YT_Chapters/main/bot_propic.png"
  title:
    en_us: "DVR Markers 2 YT Chapters Bot"
  description:
    en_us: "A telegram bot that converts your DaVinci Resolve .edl markers file into a formatted list of YouTube chapters."
  developer: "MaskenNetwork"
  main: bot

services:
  bot:
    image: dvr-markers-2-yt-chapters-bot:latest
    build: .
    container_name: dvr-markers-2-yt-chapters-bot
    restart: unless-stopped
    volumes:
      - /DATA/AppData/DVR_Markers2YT_Chapters:/app/data
